FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .


ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

RUN npm run build

EXPOSE 8000

# Run the production server
CMD ["npm", "run", "start", "--", "-p", "8000", "-H", "0.0.0.0"]