import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string()
    .valid('development', 'test', 'staging', 'production')
    .default('development'),
  PORT: Joi.number().port().default(3000),
  POSTGRES_HOST: Joi.string().required(),
  POSTGRES_PORT: Joi.number().port().required(),
  POSTGRES_USER: Joi.string().required(),
  POSTGRES_PASSWORD: Joi.string().allow('').required(),
  POSTGRES_DB: Joi.string().required(),
  DB_HOST: Joi.string().optional(),
  DB_PORT: Joi.number().port().optional(),
  DB_USERNAME: Joi.string().optional(),
  DB_PASSWORD: Joi.string().allow('').optional(),
  DB_NAME: Joi.string().optional(),
  JWT_SECRET: Joi.string().min(16).required(),
  EXPIRE_TIME: Joi.number().positive().required(),
  RESEND_PASSWORD_PIN_LIMIT: Joi.number().integer().min(0).required(),
  NODE_MAILER_USER: Joi.string().required(),
  NODE_MAILER_PASS: Joi.string().required(),
  // AWS_ACCESS_KEY_ID: Joi.string().optional(),
  // AWS_SECRET_ACCESS_KEY: Joi.string().optional(),
  // AWS_S3_REGION: Joi.string().optional(),
  // AWS_S3_BUCKET: Joi.string().optional(),
  APPWRITE_ENDPOINT: Joi.string().uri().required(),
  APPWRITE_PROJECT_ID: Joi.string().required(),
  APPWRITE_API_KEY: Joi.string().required(),
  APPWRITE_BUCKET_ID: Joi.string().required(),
  BASE_URL: Joi.string().uri().required(),
  BASE_URL_FRONTEND: Joi.string().uri().required(),
  PUBLIC_API_URL: Joi.string().uri().optional(),
  PUBLIC_PORTAL_URL: Joi.string().uri().optional(),
  PUBLIC_DOCS_URL: Joi.string().uri().optional(),
  REDIS_HOST: Joi.string().default('redis'),
  REDIS_PORT: Joi.number().port().default(6379),
  REDIS_PASSWORD: Joi.string().allow('').optional(),
  SOCIAL_TOKEN_SECRET: Joi.string().min(16).optional(),
  META_APP_ID: Joi.string().optional(),
  META_APP_SECRET: Joi.string().optional(),
  META_REDIRECT_URI: Joi.string().uri().optional(),
  SOCIAL_CONNECT_SUCCESS_URL: Joi.string().uri().optional(),
  SOCIAL_CONNECT_ERROR_URL: Joi.string().uri().optional(),
  SOCIAL_OAUTH_STATE_TTL_SECONDS: Joi.number().integer().positive().optional(),
  CONFIG_PROFILE: Joi.string().default('dev'),
});
