export const DATA_SOURCE = 'DATA_SOURCE';
export const PERMISSION_REPOSITORY = 'PERMISSION_REPOSITORY';
export const USER_PERMISSION_REPOSITORY = 'USER_PERMISSION_REPOSITORY';
export const USER_TYPE_PERMISSION_REPOSITORY =
  'USER_TYPE_PERMISSION_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const USER_ROLE_REPOSITORY = 'USER_ROLE_REPOSITORY';
export const PROPERTY_REPOSITORY = 'PROPERTY_REPOSITORY';
export const PROPERTY_PURCHASE_CONTRACT_REPOSITORY =
  'PROPERTY_PURCHASE_CONTRACT_REPOSITORY';
export const PROPERTY_STAKEHOLDER_REPOSITORY =
  'PROPERTY_STAKEHOLDER_REPOSITORY';
export const SOCIAL_ACCOUNT_REPOSITORY = 'SOCIAL_ACCOUNT_REPOSITORY';
export const SOCIAL_DESTINATION_REPOSITORY = 'SOCIAL_DESTINATION_REPOSITORY';
export const SOCIAL_OAUTH_SESSION_REPOSITORY =
  'SOCIAL_OAUTH_SESSION_REPOSITORY';
export const PROPERTY_SOCIAL_POST_REPOSITORY =
  'PROPERTY_SOCIAL_POST_REPOSITORY';
export const PROPERTY_SOCIAL_POST_TARGET_REPOSITORY =
  'PROPERTY_SOCIAL_POST_TARGET_REPOSITORY';
export const PERMISSION_GROUP_REPOSITORY = 'PERMISSION_GROUP_REPOSITORY';
export const REGISTER_PERMISSION = 'REGISTER_PERMISSION';
export const PROPERTY_ACTIVITY_REPOSITORY = 'PROPERTY_ACTIVITY_REPOSITORY';
export const PROPERTY_PURCHASE_CONTRACT_TEMPLATE_REPOSITORY =
  'PROPERTY_PURCHASE_CONTRACT_TEMPLATE_REPOSITORY';
export const PROPERTY_PURCHASE_CONTRACT_DECISION_REPOSITORY =
  'PROPERTY_PURCHASE_CONTRACT_DECISION_REPOSITORY';
export const USER_EMAIL_CONFIG_REPOSITORY = 'USER_EMAIL_CONFIG_REPOSITORY';
export const MARKETING_CAMPAIGN_REPOSITORY = 'MARKETING_CAMPAIGN_REPOSITORY';
export const MARKETING_TEMPLATE_REPOSITORY = 'MARKETING_TEMPLATE_REPOSITORY';
export const PROPERTY_QR_SCAN_REPOSITORY = 'PROPERTY_QR_SCAN_REPOSITORY';
export const PROPERTY_INQUIRY_REPOSITORY = 'PROPERTY_INQUIRY_REPOSITORY';

export const ORGANIZATION_REPOSITORY = 'ORGANIZATION_REPOSITORY';
export const NOTIFICATION_REPOSITORY = 'NOTIFICATION_REPOSITORY';
